import type { Bi } from '../i18n';

export type Category = 'web' | 'system' | 'automation' | 'lab';

export interface Project {
  slug: string;
  category: Category;
  featured?: boolean;
  title: string;
  client: Bi;
  year: string;
  status: Bi;
  url?: string;
  /** Screenshot in /public/work (generated by `npm run shots`). Systems use the FlowDiagram instead. */
  image?: string;
  tagline: Bi;
  summary: Bi;
  challenge: Bi;
  solution: Bi;
  outcome: Bi;
  features: Bi<string[]>;
  stack: string[];
  role: Bi;
  /** Steps rendered as the animated system diagram. */
  flow: Bi<string[]>;
  /** true = details reconstructed from limited files; confirm with owner (see docs/MISSING.md). */
  verify?: boolean;
}

const live: Bi = { en: 'Live', ar: 'يعمل' };
const internal: Bi = { en: 'Running internally', ar: 'يعمل داخليًا' };

export const projects: Project[] = [
  // ───────────────────────────── WEBSITES ─────────────────────────────
  {
    slug: 'alsakr-online',
    category: 'web',
    featured: true,
    title: 'Al Sakr Online',
    client: { en: 'Al Sakr Online — industrial automation parts', ar: 'الصقر أونلاين — قطع غيار الأتمتة الصناعية' },
    year: '2025–26',
    status: live,
    url: 'https://alsakronline.com',
    image: 'alsakr-online.webp',
    tagline: {
      en: 'An industrial e-commerce store with 39,000+ genuine parts — in Arabic and English.',
      ar: 'متجر إلكتروني صناعي بأكثر من 39,000 قطعة أصلية — بالعربية والإنجليزية.',
    },
    summary: {
      en: 'Egypt’s industrial automation & packaging parts store — SICK, Siemens, ABB and more — rebuilt for speed, Arabic and search.',
      ar: 'متجر قطع الأتمتة الصناعية والتغليف في مصر — SICK وSiemens وABB وغيرها — أُعيد بناؤه للسرعة والعربية ومحركات البحث.',
    },
    challenge: {
      en: 'A catalogue of tens of thousands of SKUs across a dozen brands, a slow WordPress stack, no Arabic version and engineers who search by part number, not by marketing copy.',
      ar: 'كتالوج بعشرات الآلاف من المنتجات من عشرات العلامات، وموقع WordPress بطيء، وبلا نسخة عربية، وجمهور من المهندسين يبحث برقم القطعة لا بالكلام التسويقي.',
    },
    solution: {
      en: 'I rebuilt the WooCommerce store on Elementor with a custom Arabic localisation engine, Polylang menus and slugs, Nginx + WebP performance tuning behind Cloudflare, Rank Math SEO, brand landing pages, product bundles and an embedded AI sales assistant. Product data is imported and enriched by Python scripts and n8n.',
      ar: 'أعدت بناء متجر WooCommerce على Elementor مع محرك تعريب مخصّص، وقوائم وروابط عربية عبر Polylang، وتحسين أداء Nginx وصور WebP خلف Cloudflare، وسيو Rank Math، وصفحات للعلامات التجارية، وحزم منتجات، ومساعد مبيعات بالذكاء الاصطناعي. بيانات المنتجات تُستورد وتُثرى عبر سكربتات Python وn8n.',
    },
    outcome: {
      en: '39,000+ products live in two languages, a catalogue that updates from data instead of by hand, and the foundation for the SEO content factory and AI widget.',
      ar: 'أكثر من 39,000 منتج متاح بلغتين، وكتالوج يتحدّث من البيانات لا يدويًا، وأساس لمصنع محتوى السيو ومساعد الذكاء الاصطناعي.',
    },
    features: {
      en: ['39,000+ SKUs, 10+ brands', 'Custom Arabic localisation engine', 'Nginx / WebP / Cloudflare performance', 'Brand & bundle landing pages', 'AI assistant + WhatsApp RFQ'],
      ar: ['أكثر من 39,000 منتج و10+ علامات', 'محرك تعريب مخصّص', 'أداء Nginx وWebP وCloudflare', 'صفحات العلامات والحزم', 'مساعد ذكاء اصطناعي وطلب عرض سعر عبر واتساب'],
    },
    stack: ['WordPress', 'WooCommerce', 'Elementor', 'Polylang', 'Rank Math', 'Nginx', 'Cloudflare', 'Python', 'n8n'],
    role: { en: 'Strategy, build, SEO, automation', ar: 'الاستراتيجية والبناء والسيو والأتمتة' },
    flow: {
      en: ['Supplier data', 'Python import', 'WooCommerce', 'AR localisation', 'SEO + Cloudflare', 'Customer / RFQ'],
      ar: ['بيانات الموردين', 'استيراد Python', 'WooCommerce', 'التعريب', 'السيو وCloudflare', 'العميل / طلب السعر'],
    },
  },
  {
    slug: 'nexumotion',
    category: 'web',
    featured: true,
    title: 'NexuMotion',
    client: { en: 'NexuMotion — industrial automation spare parts', ar: 'نيكسو موشن — قطع غيار الأتمتة الصناعية' },
    year: '2026',
    status: live,
    url: 'https://nexumotion.com',
    image: 'nexumotion.webp',
    tagline: {
      en: 'An Arabic-first parts brand for Egypt, the Middle East and Africa — with a social engine that runs daily.',
      ar: 'علامة قطع غيار بالعربية أولًا لمصر والشرق الأوسط وأفريقيا — مع محرك سوشيال يعمل يوميًا.',
    },
    summary: {
      en: 'PLCs, drives, HMIs and sensors — sold with the technical data an engineer needs to choose them.',
      ar: 'وحدات PLC ومغيّرات سرعة وشاشات HMI وحسّاسات — مع البيانات الفنية التي يحتاجها المهندس للاختيار.',
    },
    challenge: {
      en: 'Launch a new brand into a market dominated by old distributors, in Arabic first, and stay visible every day without a content team.',
      ar: 'إطلاق علامة جديدة في سوق يسيطر عليه موزّعون قدامى، بالعربية أولًا، والبقاء ظاهرًا يوميًا بدون فريق محتوى.',
    },
    solution: {
      en: 'A Next.js site served through Cloudflare, structured around product families and engineering data, connected to n8n workflows that turn site content into daily social posts through Postiz.',
      ar: 'موقع Next.js عبر Cloudflare، مبني حول عائلات المنتجات والبيانات الهندسية، ومتصل بمسارات n8n تحوّل محتوى الموقع إلى منشورات يومية عبر Postiz.',
    },
    outcome: {
      en: 'A credible bilingual brand presence and a publishing rhythm that does not depend on anyone remembering to post.',
      ar: 'حضور موثوق بلغتين، وإيقاع نشر لا يعتمد على تذكّر أحد للنشر.',
    },
    features: {
      en: ['Arabic-first, RTL', '17,332 searchable specifications across 11 brands', 'AI parts assistant', 'Site → social automation', 'Daily posting via Postiz', 'Cloudflare edge'],
      ar: ['العربية أولًا من اليمين لليسار', '17,332 مواصفة قابلة للبحث لـ 11 علامة', 'مساعد ذكي لاختيار القطع', 'أتمتة من الموقع إلى السوشيال', 'نشر يومي عبر Postiz', 'Cloudflare'],
    },
    stack: ['Next.js', 'Cloudflare', 'n8n', 'Postiz', 'Gemini'],
    role: { en: 'Brand, site, content automation', ar: 'الهوية والموقع وأتمتة المحتوى' },
    flow: {
      en: ['Product data', 'Next.js site', 'n8n picks a page', 'AI writes post', 'Approval', 'Postiz publishes'],
      ar: ['بيانات المنتج', 'موقع Next.js', 'n8n يختار صفحة', 'الذكاء الاصطناعي يكتب', 'موافقة', 'Postiz ينشر'],
    },
  },
  {
    slug: 'iconic-mach',
    category: 'web',
    title: 'Iconic Mach Engineering',
    client: { en: 'Iconic Mach Engineering', ar: 'أيكونيك ماك للهندسة' },
    year: '2026',
    status: live,
    url: 'https://iconicmach.com/en/',
    image: 'iconic-mach.webp',
    tagline: {
      en: 'A bilingual corporate site for a production-line and conveyor engineering company.',
      ar: 'موقع شركة ثنائي اللغة لشركة هندسة خطوط إنتاج وأنظمة نقل.',
    },
    summary: {
      en: 'Production lines, conveyor systems and industrial automation — presented for factory owners and procurement teams.',
      ar: 'خطوط الإنتاج وأنظمة النقل والأتمتة الصناعية — معروضة لأصحاب المصانع وفرق المشتريات.',
    },
    challenge: {
      en: 'Explain complex engineering capability clearly to two audiences — Arabic-speaking factory owners and English-speaking partners — and turn visits into project enquiries.',
      ar: 'شرح قدرات هندسية معقّدة بوضوح لجمهورين — أصحاب مصانع يتحدثون العربية وشركاء يتحدثون الإنجليزية — وتحويل الزيارات إلى استفسارات مشاريع.',
    },
    solution: {
      en: 'A structured corporate site with product categories, industries, projects and clear quote paths in both languages, served through Cloudflare.',
      ar: 'موقع شركة منظّم يضم فئات المنتجات والقطاعات والمشاريع ومسارات واضحة لطلب عروض الأسعار باللغتين، عبر Cloudflare.',
    },
    outcome: {
      en: 'A professional digital front door that later became the structural reference for the Al Sakr Conveying site.',
      ar: 'واجهة رقمية احترافية أصبحت لاحقًا المرجع الهيكلي لموقع الصقر لأنظمة النقل.',
    },
    features: {
      en: ['EN / AR', 'Product & industry structure', 'Project showcase', 'Quote-request paths'],
      ar: ['إنجليزي / عربي', 'هيكل للمنتجات والقطاعات', 'عرض المشاريع', 'مسارات طلب عرض السعر'],
    },
    stack: ['Cloudflare', 'Bilingual CMS'],
    role: { en: 'Design & build', ar: 'التصميم والبناء' },
    flow: {
      en: ['Visitor', 'Industry page', 'Product line', 'Project proof', 'Quote request'],
      ar: ['الزائر', 'صفحة القطاع', 'خط الإنتاج', 'دليل المشروع', 'طلب عرض سعر'],
    },
    verify: true,
  },
  {
    slug: 'alsakr-conveying',
    category: 'web',
    featured: true,
    title: 'Al Sakr Conveying',
    client: { en: 'Al Sakr Conveying — conveyor systems', ar: 'الصقر لأنظمة النقل والسيور' },
    year: '2026',
    status: live,
    url: 'https://alsakronline-cyber.github.io/',
    image: 'alsakr-conveying.webp',
    tagline: {
      en: 'A video-first industrial site built from the factory’s own footage — Arabic and English at full parity.',
      ar: 'موقع صناعي يعتمد على الفيديو من لقطات المصنع نفسه — عربي وإنجليزي بنفس المستوى.',
    },
    summary: {
      en: 'Flex-chain, spiral, modular-belt and gripper conveyors shown in motion, not described in paragraphs.',
      ar: 'سيور السلاسل المرنة واللولبية والأحزمة المعيارية والقابضة — تُعرض وهي تعمل، لا في فقرات.',
    },
    challenge: {
      en: 'Conveyors are bought by people who need to see them move. The company had raw factory videos and no website — and needed to look like a premium engineering partner.',
      ar: 'السيور يشتريها من يحتاج أن يراها تتحرك. كانت لدى الشركة فيديوهات خام من المصنع ولا موقع — وتحتاج أن تظهر كشريك هندسي متميّز.',
    },
    solution: {
      en: 'An Astro static site with an encoding pipeline that turns raw footage into lightweight looping video and posters, a filterable product catalogue, product detail pages with specs, industries, projects and WhatsApp/quote CTAs — RTL treated as first-class.',
      ar: 'موقع Astro ثابت مع خط معالجة يحوّل اللقطات الخام إلى فيديو خفيف متكرّر وصور غلاف، وكتالوج قابل للتصفية، وصفحات منتجات بالمواصفات، وقطاعات ومشاريع، وأزرار واتساب وطلب عرض سعر — مع معاملة العربية كلغة أساسية.',
    },
    outcome: {
      en: 'All pages live in EN and AR from v1, hosted for free, with a Lighthouse ≥ 90 mobile target despite heavy video.',
      ar: 'كل الصفحات تعمل بالعربية والإنجليزية من الإصدار الأول، باستضافة مجانية، مع هدف Lighthouse ‏90+ على الموبايل رغم الفيديو.',
    },
    features: {
      en: ['Video hero from factory footage', 'Filterable catalogue', 'Specs & applications per product', 'Full AR / EN parity', 'Static hosting'],
      ar: ['واجهة فيديو من لقطات المصنع', 'كتالوج قابل للتصفية', 'مواصفات وتطبيقات لكل منتج', 'تكافؤ كامل عربي / إنجليزي', 'استضافة ثابتة'],
    },
    stack: ['Astro', 'TypeScript', 'FFmpeg', 'GitHub Pages', 'Netlify'],
    role: { en: 'Design, video pipeline, build', ar: 'التصميم وخط الفيديو والبناء' },
    flow: {
      en: ['Raw factory video', 'FFmpeg encode', 'Astro pages', 'AR + EN', 'WhatsApp / quote'],
      ar: ['فيديو خام', 'ترميز FFmpeg', 'صفحات Astro', 'عربي + إنجليزي', 'واتساب / عرض سعر'],
    },
  },
  {
    slug: 'walaa-3d',
    category: 'web',
    featured: true,
    title: 'Walaa 3D Animation',
    client: { en: 'Walaa Ramadan — 3D product animator', ar: 'ولاء رمضان — مصمّمة رسوم ثلاثية الأبعاد للمنتجات' },
    year: '2026',
    status: live,
    url: 'https://walaa3d.studio',
    image: 'walaa-3d.webp',
    tagline: {
      en: 'A premium, video-led portfolio and brand for a 3D product animator.',
      ar: 'معرض أعمال وهوية متميّزة يقودها الفيديو لمصمّمة رسوم ثلاثية الأبعاد للمنتجات.',
    },
    summary: {
      en: 'Brand, logo and site: “Bring your product to life in 3D.”',
      ar: 'الهوية والشعار والموقع: «أعطِ منتجك الحياة بالأبعاد الثلاثية».',
    },
    challenge: {
      en: 'Position a talented 3D animator against generic “AI video creators” and make the work itself — not the copy — do the selling.',
      ar: 'تمييز مصمّمة موهوبة عن «صنّاع فيديو الذكاء الاصطناعي» العامّين، وجعل الأعمال نفسها — لا النصوص — هي التي تبيع.',
    },
    solution: {
      en: 'Positioning (“More than animation. I understand products.”), an isometric-cube W logo, a light gray and gold editorial design, and an Astro site with a video-led portfolio, service hierarchy, process and SEO built in.',
      ar: 'تموضع («أكثر من مجرد رسوم متحركة. أنا أفهم المنتجات»)، وشعار مكعّب متساوي القياس على شكل W، وتصميم تحريري رمادي فاتح وذهبي، وموقع Astro بمعرض يقوده الفيديو وترتيب خدمات ومراحل عمل وسيو مدمج.',
    },
    outcome: {
      en: 'A live studio site on its own domain with a clear offer, ready for launch campaigns and outreach.',
      ar: 'موقع استوديو حيّ على دومين خاص بعرض واضح، جاهز لحملات الإطلاق والتواصل.',
    },
    features: {
      en: ['Brand & logo', 'Video-led portfolio', 'Service hierarchy & process', 'SEO title strategy', 'Custom domain'],
      ar: ['الهوية والشعار', 'معرض يقوده الفيديو', 'ترتيب الخدمات ومراحل العمل', 'استراتيجية عناوين السيو', 'دومين مخصّص'],
    },
    stack: ['Astro', 'TypeScript', 'FFmpeg', 'GitHub'],
    role: { en: 'Branding, design, build', ar: 'الهوية والتصميم والبناء' },
    flow: {
      en: ['Positioning', 'Logo & palette', 'Video portfolio', 'Astro site', 'Enquiry'],
      ar: ['التموضع', 'الشعار والألوان', 'معرض الفيديو', 'موقع Astro', 'استفسار'],
    },
  },
  {
    slug: 'nutrasakr',
    category: 'web',
    title: 'NutraSakr',
    client: { en: 'NutraSakr — healthcare & nutraceuticals', ar: 'نيوترا صقر — الرعاية الصحية والمكمّلات' },
    year: '2026',
    status: live,
    url: 'https://nutrasakr.com',
    image: 'nutrasakr.webp',
    tagline: {
      en: 'A 20-page bilingual corporate site for a nutraceutical and pharmaceutical company — with zero frameworks.',
      ar: 'موقع شركة ثنائي اللغة من 20 صفحة لشركة مكمّلات وأدوية — بدون أي إطار عمل.',
    },
    summary: {
      en: 'Manufacturing, private label, export, distributors, certifications and research — for Egypt, MENA and international buyers.',
      ar: 'التصنيع والعلامة الخاصة والتصدير والموزّعون والشهادات والأبحاث — لمصر والشرق الأوسط والمشترين الدوليين.',
    },
    challenge: {
      en: 'A B2B health brand needs to look regulated and trustworthy to distributors abroad while staying fast and cheap to host.',
      ar: 'علامة صحية B2B تحتاج أن تبدو منظّمة وموثوقة للموزّعين في الخارج، مع البقاء سريعة ورخيصة الاستضافة.',
    },
    solution: {
      en: 'Hand-written HTML, CSS and vanilla JS with JSON-driven Arabic/English content, dedicated pages for every B2B journey (private label, export, distributors, request info) and full SEO basics.',
      ar: 'HTML وCSS وJavaScript مكتوبة يدويًا، مع محتوى عربي/إنجليزي يُحمَّل من JSON، وصفحات مخصّصة لكل رحلة B2B (علامة خاصة، تصدير، موزّعون، طلب معلومات)، وأساسيات سيو كاملة.',
    },
    outcome: {
      en: 'A complete corporate presence on nutrasakr.com that loads fast on any connection and can be hosted anywhere.',
      ar: 'حضور مؤسسي متكامل على nutrasakr.com يُحمَّل بسرعة على أي اتصال ويمكن استضافته في أي مكان.',
    },
    features: {
      en: ['~20 pages', 'JSON-driven AR / EN', 'Private-label & export funnels', 'Certifications & research', 'No framework, no build step'],
      ar: ['نحو 20 صفحة', 'عربي / إنجليزي من JSON', 'مسارات العلامة الخاصة والتصدير', 'الشهادات والأبحاث', 'بدون إطار عمل أو بناء'],
    },
    stack: ['HTML5', 'CSS3', 'Vanilla JS', 'JSON i18n', 'Hostinger'],
    role: { en: 'Design & build', ar: 'التصميم والبناء' },
    flow: {
      en: ['Distributor', 'Capabilities', 'Certifications', 'Private label / export', 'Request info'],
      ar: ['الموزّع', 'القدرات', 'الشهادات', 'علامة خاصة / تصدير', 'طلب معلومات'],
    },
  },
  {
    slug: 'effat',
    category: 'web',
    title: 'Effat Group',
    client: { en: 'Effat Group', ar: 'مجموعة عفت' },
    year: '2026',
    status: { en: 'In development', ar: 'قيد التطوير' },
    tagline: {
      en: 'An Arabic-first commerce platform with a 3D hero, Arabic-aware search and cash-on-delivery as a first-class citizen.',
      ar: 'منصة تجارة بالعربية أولًا مع واجهة ثلاثية الأبعاد، وبحث يفهم العربية، والدفع عند الاستلام كخيار أساسي.',
    },
    summary: {
      en: 'Next.js 15 + Payload CMS in one deploy, with Paymob, Fawry, COD and WhatsApp order updates.',
      ar: 'Next.js 15 مع Payload CMS في نشر واحد، مع Paymob وفوري والدفع عند الاستلام وتحديثات الطلب عبر واتساب.',
    },
    challenge: {
      en: 'Egyptian shoppers search in Arabic with inconsistent spelling, pay in cash and expect updates on WhatsApp — most off-the-shelf stores handle none of that well.',
      ar: 'المتسوّق المصري يبحث بالعربية بإملاء غير موحّد، ويدفع نقدًا، وينتظر التحديثات على واتساب — ومعظم المتاجر الجاهزة لا تتعامل مع ذلك جيدًا.',
    },
    solution: {
      en: 'A locked architecture: Next.js 15 App Router with Payload CMS 3 on Postgres, Meilisearch tuned for Arabic normalisation, Cloudflare R2 media, next-intl with Arabic as default, a budgeted React Three Fiber hero, Paymob/Fawry/COD payments and WhatsApp Cloud API notifications.',
      ar: 'معمارية محدّدة: Next.js 15 مع Payload CMS 3 على Postgres، وMeilisearch مضبوط لتوحيد الإملاء العربي، ووسائط على Cloudflare R2، وnext-intl بالعربية افتراضيًا، وواجهة React Three Fiber بميزانية أداء، ودفع Paymob وفوري والدفع عند الاستلام، وإشعارات WhatsApp Cloud API.',
    },
    outcome: {
      en: 'Architecture and design system complete; platform in active development.',
      ar: 'المعمارية ونظام التصميم مكتملان، والمنصّة قيد التطوير النشط.',
    },
    features: {
      en: ['Arabic-normalised search', 'COD + Paymob + Fawry', 'WhatsApp order updates', '3D product hero', 'Admin CMS in the same app'],
      ar: ['بحث يوحّد الإملاء العربي', 'الدفع عند الاستلام + Paymob + فوري', 'تحديثات الطلب عبر واتساب', 'واجهة منتج ثلاثية الأبعاد', 'لوحة إدارة داخل التطبيق نفسه'],
    },
    stack: ['Next.js 15', 'React 19', 'Payload CMS', 'PostgreSQL', 'Meilisearch', 'Tailwind', 'Three.js', 'Cloudflare R2'],
    role: { en: 'Architecture, design, build', ar: 'المعمارية والتصميم والبناء' },
    flow: {
      en: ['Shopper (AR)', 'Arabic search', 'Product + 3D', 'Checkout / COD', 'WhatsApp updates'],
      ar: ['المتسوّق', 'بحث عربي', 'المنتج + 3D', 'الدفع / عند الاستلام', 'تحديثات واتساب'],
    },
  },

  // ───────────────────────────── SYSTEMS ─────────────────────────────
  {
    slug: 'qualifay',
    category: 'system',
    featured: true,
    title: 'Qualifay',
    client: { en: 'Own product — B2B SaaS', ar: 'منتج خاص — SaaS للشركات' },
    year: '2026',
    status: { en: 'Private beta', ar: 'نسخة تجريبية خاصة' },
    tagline: {
      en: 'AI-powered B2B lead generation and WhatsApp CRM for the Egyptian market.',
      ar: 'توليد عملاء B2B بالذكاء الاصطناعي ونظام إدارة علاقات عبر واتساب للسوق المصري.',
    },
    summary: {
      en: 'Scrape → enrich → AI-qualify → human approves → WhatsApp outreach → AI handles replies → books the meeting.',
      ar: 'جمع → إثراء → تأهيل بالذكاء الاصطناعي → موافقة بشرية → تواصل واتساب → ردود ذكية → حجز الاجتماع.',
    },
    challenge: {
      en: 'Egyptian B2B sales still runs on spreadsheets and cold calls. Lead lists are stale, follow-ups are forgotten and WhatsApp — where deals actually happen — is unmanaged.',
      ar: 'مبيعات B2B في مصر ما زالت تعتمد على الجداول والمكالمات الباردة. قوائم العملاء قديمة، والمتابعات تُنسى، وواتساب — حيث تُغلق الصفقات فعلًا — بلا إدارة.',
    },
    solution: {
      en: 'A multi-tenant SaaS: FastAPI + Celery workers, a Next.js 14 RTL dashboard, 9 scraping modules (Google Maps, business sites, directories, tenders…), 16 AI agents (quality gate, BANT scorer, consent checker, AIDA writer, intent classifier, responder, appointment booker…), WhatsApp via Evolution API with warm-up limits, Qdrant RAG per tenant and Paymob/Fawry/Stripe billing. No message is sent without human approval.',
      ar: 'منصّة SaaS متعددة المستأجرين: FastAPI مع عمّال Celery، ولوحة Next.js 14 بالعربية، و9 وحدات جمع بيانات (خرائط جوجل، مواقع الشركات، الأدلّة، المناقصات…)، و16 وكيل ذكاء اصطناعي (بوابة جودة، تقييم BANT، فحص الموافقة، كاتب AIDA، مصنّف النوايا، الرد الآلي، حجز المواعيد…)، وواتساب عبر Evolution API مع حدود الإحماء، وRAG عبر Qdrant لكل عميل، ودفع Paymob وفوري وStripe. لا تُرسل أي رسالة دون موافقة بشرية.',
    },
    outcome: {
      en: 'A working end-to-end pipeline from scraped company to booked appointment, with Starter / Growth / Agency tiers designed for launch.',
      ar: 'خط عمل كامل من الشركة المجموعة بياناتها حتى الموعد المحجوز، مع باقات Starter وGrowth وAgency جاهزة للإطلاق.',
    },
    features: {
      en: ['9 scraping modules', '16 AI agents', 'Human-in-the-loop approvals', 'WhatsApp warm-up & limits', 'Multi-tenant, white-label tier'],
      ar: ['9 وحدات جمع بيانات', '16 وكيل ذكاء اصطناعي', 'موافقات بشرية', 'إحماء وحدود واتساب', 'متعدد المستأجرين مع باقة بعلامة خاصة'],
    },
    stack: ['FastAPI', 'Celery', 'Redis', 'PostgreSQL', 'Next.js 14', 'Evolution API', 'Qdrant', 'Groq', 'OpenRouter', 'Docker'],
    role: { en: 'Founder, product, full-stack', ar: 'المؤسس والمنتج والتطوير الكامل' },
    flow: {
      en: ['Scrape', 'Enrich', 'AI score (BANT)', 'Human approve', 'WhatsApp', 'AI reply', 'Meeting booked'],
      ar: ['جمع', 'إثراء', 'تقييم BANT', 'موافقة بشرية', 'واتساب', 'رد ذكي', 'حجز اجتماع'],
    },
  },
  {
    slug: 'erpnext-alsakr',
    category: 'system',
    title: 'ERPNext for Al Sakr',
    client: { en: 'Al Sakr — industrial distribution', ar: 'الصقر — توزيع صناعي' },
    year: '2026',
    status: internal,
    tagline: {
      en: 'One source of truth for items, quotations, purchasing and stock — connected to the website.',
      ar: 'مصدر واحد للحقيقة للأصناف وعروض الأسعار والمشتريات والمخزون — متصل بالموقع.',
    },
    summary: {
      en: 'An ERPNext deployment shaped around how an industrial parts distributor actually quotes and buys.',
      ar: 'تطبيق ERPNext مصمّم حول الطريقة التي يسعّر بها ويشتري موزّع قطع صناعية فعلًا.',
    },
    challenge: {
      en: 'Quotations, supplier prices and stock lived in dozens of spreadsheets. The same item had different codes in sales, purchasing and on the website.',
      ar: 'عروض الأسعار وأسعار الموردين والمخزون كانت موزّعة على عشرات الجداول، والصنف نفسه له أكواد مختلفة في المبيعات والمشتريات والموقع.',
    },
    solution: {
      en: 'ERPNext configured for items, customers, suppliers, quotations, purchase and stock, with data migrated from the spreadsheets and integrations so product data can flow between the ERP and the WooCommerce store.',
      ar: 'ERPNext مُعدّ للأصناف والعملاء والموردين وعروض الأسعار والمشتريات والمخزون، مع ترحيل البيانات من الجداول، وربط يسمح بتدفّق بيانات المنتجات بين الـ ERP والمتجر.',
    },
    outcome: {
      en: 'Quoting and purchasing in one system, with consistent item data across sales and the website.',
      ar: 'التسعير والمشتريات في نظام واحد، مع بيانات أصناف موحّدة بين المبيعات والموقع.',
    },
    features: {
      en: ['Item & supplier master data', 'Quotation → order flow', 'Stock & purchasing', 'Spreadsheet migration', 'Website integration'],
      ar: ['بيانات رئيسية للأصناف والموردين', 'من عرض السعر إلى الطلب', 'المخزون والمشتريات', 'ترحيل من الجداول', 'ربط بالموقع'],
    },
    stack: ['ERPNext', 'Frappe', 'MariaDB', 'Python', 'REST API', 'n8n'],
    role: { en: 'Implementation & integration', ar: 'التطبيق والربط' },
    flow: {
      en: ['Spreadsheets', 'Migration', 'ERPNext', 'Quotation', 'Purchase / stock', 'Website sync'],
      ar: ['الجداول', 'الترحيل', 'ERPNext', 'عرض السعر', 'شراء / مخزون', 'مزامنة الموقع'],
    },
    verify: true,
  },
  {
    slug: 'alsakr-analytics',
    category: 'system',
    title: 'Al Sakr Analytics',
    client: { en: 'Al Sakr — sales & marketing', ar: 'الصقر — المبيعات والتسويق' },
    year: '2026',
    status: internal,
    tagline: {
      en: 'Ad spend, invoices and sales targets in one view — so marketing decisions follow revenue, not clicks.',
      ar: 'إنفاق الإعلانات والفواتير وأهداف المبيعات في عرض واحد — لتتبع قرارات التسويق الإيراد، لا النقرات.',
    },
    summary: {
      en: 'An analytics system joining Meta campaign exports, invoice summaries and sales data into dashboards and automated reports.',
      ar: 'نظام تحليلات يجمع بيانات حملات Meta وملخّصات الفواتير وبيانات المبيعات في لوحات وتقارير تلقائية.',
    },
    challenge: {
      en: 'Ads were judged by platform metrics while revenue sat in invoices. Nobody could answer “which campaign actually made money?”',
      ar: 'كانت الإعلانات تُقيَّم بمقاييس المنصّة بينما الإيراد في الفواتير. لم يستطع أحد الإجابة: «أي حملة جلبت المال فعلًا؟»',
    },
    solution: {
      en: 'Python pipelines that ingest campaign CSVs, invoice summaries and sales targets, normalise them, and feed dashboards plus an n8n reporting workflow that sends the numbers that changed.',
      ar: 'خطوط Python تستقبل ملفات الحملات وملخّصات الفواتير وأهداف المبيعات، وتوحّدها، وتغذّي لوحات البيانات ومسار تقارير n8n يرسل الأرقام التي تغيّرت.',
    },
    outcome: {
      en: 'Spend, sales and targets compared side by side, with reports arriving automatically instead of being assembled by hand.',
      ar: 'مقارنة الإنفاق والمبيعات والأهداف جنبًا إلى جنب، مع تقارير تصل تلقائيًا بدل تجميعها يدويًا.',
    },
    features: {
      en: ['Meta Ads ingestion', 'Invoice & sales joins', 'Target tracking', 'Dashboards', 'Automated reports'],
      ar: ['استيراد بيانات Meta Ads', 'ربط الفواتير والمبيعات', 'تتبّع الأهداف', 'لوحات بيانات', 'تقارير تلقائية'],
    },
    stack: ['Python', 'pandas', 'Google Sheets', 'Meta Ads', 'n8n', 'Looker Studio'],
    role: { en: 'Data, dashboards, automation', ar: 'البيانات واللوحات والأتمتة' },
    flow: {
      en: ['Meta Ads', 'Invoices', 'Sales targets', 'Python ETL', 'Dashboard', 'Daily report'],
      ar: ['Meta Ads', 'الفواتير', 'أهداف المبيعات', 'معالجة Python', 'لوحة البيانات', 'تقرير يومي'],
    },
    verify: true,
  },
  {
    slug: 'scraping-engine',
    category: 'system',
    title: 'Scraping & Market-Intel Engine',
    client: { en: 'Al Sakr + Qualifay', ar: 'الصقر + Qualifay' },
    year: '2025–26',
    status: internal,
    tagline: {
      en: 'Scrapers that feed catalogues, SEO and sales — product data, SERPs, competitors and B2B leads.',
      ar: 'أدوات جمع بيانات تغذّي الكتالوجات والسيو والمبيعات — بيانات المنتجات ونتائج البحث والمنافسين والعملاء.',
    },
    summary: {
      en: 'A family of Python scrapers and n8n jobs that turn the open web into structured, usable data.',
      ar: 'مجموعة من أدوات Python ومهام n8n تحوّل الويب المفتوح إلى بيانات منظّمة قابلة للاستخدام.',
    },
    challenge: {
      en: 'Thousands of products needed specs and images, SEO needed competitor and SERP data, and sales needed lists of real factories — all by hand, all out of date.',
      ar: 'آلاف المنتجات تحتاج مواصفات وصورًا، والسيو يحتاج بيانات المنافسين ونتائج البحث، والمبيعات تحتاج قوائم مصانع حقيقية — كلها يدوية وقديمة.',
    },
    solution: {
      en: 'SERP and WooCommerce scrapers, supplier stock/price scrapers that generate import files and bundles, competitor-intel workflows, and B2B lead scrapers (e.g. industrial-zone company lists) — with polite delays, retries and clean CSV/XLSX output.',
      ar: 'أدوات لجمع نتائج البحث ومنتجات WooCommerce، وأدوات لأسعار ومخزون الموردين تولّد ملفات الاستيراد والحزم، ومسارات لتحليل المنافسين، وأدوات جمع عملاء B2B (مثل قوائم شركات المناطق الصناعية) — مع تأخير مهذّب وإعادة محاولة ومخرجات CSV/XLSX نظيفة.',
    },
    outcome: {
      en: 'Product imports, keyword research and lead lists produced in minutes instead of days — and reused inside Qualifay.',
      ar: 'استيراد المنتجات وأبحاث الكلمات وقوائم العملاء تُنجز في دقائق بدل أيام — وأُعيد استخدامها داخل Qualifay.',
    },
    features: {
      en: ['SERP scraper', 'Product & stock scrapers', 'Competitor intel', 'B2B lead lists', 'CSV / XLSX / WooCommerce output'],
      ar: ['جمع نتائج البحث', 'جمع المنتجات والمخزون', 'تحليل المنافسين', 'قوائم عملاء B2B', 'مخرجات CSV / XLSX / WooCommerce'],
    },
    stack: ['Python', 'Playwright', 'Puppeteer', 'BeautifulSoup', 'n8n', 'pandas'],
    role: { en: 'Engineering', ar: 'الهندسة' },
    flow: {
      en: ['Target sites', 'Scraper', 'Clean & dedupe', 'Enrich', 'Store / import', 'SEO · Sales · Catalogue'],
      ar: ['المواقع المستهدفة', 'أداة الجمع', 'تنظيف وإزالة التكرار', 'إثراء', 'تخزين / استيراد', 'سيو · مبيعات · كتالوج'],
    },
  },

  // ───────────────────────────── AUTOMATIONS ─────────────────────────────
  {
    slug: 'seo-content-factory',
    category: 'automation',
    featured: true,
    title: 'SEO Content Factory',
    client: { en: 'Al Sakr Online', ar: 'الصقر أونلاين' },
    year: '2026',
    status: internal,
    tagline: {
      en: 'Ten n8n workflows that research, write, check, publish, link and report — in English and Arabic.',
      ar: 'عشرة مسارات n8n تبحث وتكتب وتراجع وتنشر وتربط وتقدّم التقارير — بالإنجليزية والعربية.',
    },
    summary: {
      en: 'An engineer-to-engineer content engine for a 39,000-product industrial catalogue.',
      ar: 'محرك محتوى من مهندس إلى مهندس لكتالوج صناعي من 39,000 منتج.',
    },
    challenge: {
      en: 'Industrial buyers search for exact part numbers and technical answers. Writing that content by hand for tens of thousands of products — in two languages — is impossible.',
      ar: 'المشترون الصناعيون يبحثون عن أرقام قطع وإجابات فنية دقيقة. كتابة هذا المحتوى يدويًا لعشرات الآلاف من المنتجات — بلغتين — مستحيلة.',
    },
    solution: {
      en: 'WF-01 keyword discovery · WF-02 competitor intel · WF-03 content generation · WF-04 QA check · WF-05 WordPress publisher · WF-06 social automation · WF-07 SEO monitoring · WF-08 internal linking · WF-09 product enrichment · WF-10 reporting. Strict tone rules, banned-word lists, English first then Arabic, and every new article saved as a draft for technical review.',
      ar: 'WF-01 اكتشاف الكلمات · WF-02 تحليل المنافسين · WF-03 توليد المحتوى · WF-04 فحص الجودة · WF-05 النشر على WordPress · WF-06 أتمتة السوشيال · WF-07 مراقبة السيو · WF-08 الربط الداخلي · WF-09 إثراء المنتجات · WF-10 التقارير. مع قواعد نبرة صارمة، وقائمة كلمات ممنوعة، والإنجليزية أولًا ثم العربية، وكل مقال جديد يُحفظ كمسودة للمراجعة الفنية.',
    },
    outcome: {
      en: 'A repeatable pipeline: 2–3 reviewed articles a week, enriched product pages and automatic internal links, with a human always approving what goes live.',
      ar: 'خط إنتاج قابل للتكرار: 2–3 مقالات مُراجَعة أسبوعيًا، وصفحات منتجات مُثراة، وربط داخلي تلقائي، مع موافقة بشرية دائمة على ما يُنشر.',
    },
    features: {
      en: ['10 chained workflows', 'Bilingual EN → AR', 'QA gate & banned words', 'Draft-first publishing', 'Internal-linking bot'],
      ar: ['10 مسارات متصلة', 'ثنائي اللغة من الإنجليزية للعربية', 'بوابة جودة وكلمات ممنوعة', 'النشر كمسودة أولًا', 'روبوت ربط داخلي'],
    },
    stack: ['n8n', 'WordPress REST', 'Gemini', 'Claude', 'Search Console', 'Python'],
    role: { en: 'System design & build', ar: 'تصميم النظام وبناؤه' },
    flow: {
      en: ['Keywords', 'Competitors', 'AI draft', 'QA gate', 'WP draft', 'Human review', 'Publish + link'],
      ar: ['الكلمات', 'المنافسون', 'مسودة ذكية', 'بوابة الجودة', 'مسودة WP', 'مراجعة بشرية', 'نشر + ربط'],
    },
  },
  {
    slug: 'social-autopilot',
    category: 'automation',
    featured: true,
    title: 'Social Autopilot',
    client: { en: 'Al Sakr Online + NexuMotion', ar: 'الصقر أونلاين + نيكسو موشن' },
    year: '2026',
    status: internal,
    tagline: {
      en: 'Blog and site content becomes daily social posts — approved from Telegram, published by Postiz.',
      ar: 'محتوى المدوّنة والموقع يتحوّل إلى منشورات يومية — تُعتمد من تيليجرام وتُنشر عبر Postiz.',
    },
    summary: {
      en: 'Two brands, multiple platforms, one approval tap.',
      ar: 'علامتان، ومنصّات متعددة، وضغطة موافقة واحدة.',
    },
    challenge: {
      en: 'Posting consistently across platforms for two brands took hours a week and stopped whenever someone got busy.',
      ar: 'النشر المنتظم على عدة منصّات لعلامتين كان يستهلك ساعات أسبوعيًا ويتوقف كلما انشغل أحد.',
    },
    solution: {
      en: 'n8n workflows that pick a page or article, write platform-specific captions with an AI model (with Gemini fallback), generate the image, send a preview to Telegram for approve / edit / reject, then publish through self-hosted Postiz — with a content gate, CTA rules, durable memory to avoid repeats and an automatic retry workflow.',
      ar: 'مسارات n8n تختار صفحة أو مقالًا، وتكتب نصوصًا مخصّصة لكل منصّة بنموذج ذكاء اصطناعي (مع بديل Gemini)، وتولّد الصورة، وترسل معاينة إلى تيليجرام للموافقة أو التعديل أو الرفض، ثم تنشر عبر Postiz المستضاف ذاتيًا — مع بوابة محتوى، وقواعد للدعوة للإجراء، وذاكرة دائمة لمنع التكرار، ومسار إعادة محاولة تلقائي.',
    },
    outcome: {
      en: 'A daily publishing rhythm for two brands that takes one tap to approve.',
      ar: 'إيقاع نشر يومي لعلامتين يحتاج ضغطة واحدة للموافقة.',
    },
    features: {
      en: ['Site → social and blog → social', 'Telegram approval gate', 'AI fallback chain', 'No-repeat memory', 'Auto-retry'],
      ar: ['من الموقع والمدوّنة إلى السوشيال', 'بوابة موافقة تيليجرام', 'سلسلة بدائل للذكاء الاصطناعي', 'ذاكرة تمنع التكرار', 'إعادة محاولة تلقائية'],
    },
    stack: ['n8n', 'Postiz', 'Telegram Bot API', 'Gemini', 'WordPress', 'Docker'],
    role: { en: 'System design & build', ar: 'تصميم النظام وبناؤه' },
    flow: {
      en: ['New page / post', 'AI caption', 'Image', 'Telegram approve', 'Postiz', 'All platforms'],
      ar: ['صفحة / مقال جديد', 'نص ذكي', 'صورة', 'موافقة تيليجرام', 'Postiz', 'كل المنصّات'],
    },
  },
  {
    slug: 'ops-monitor',
    category: 'automation',
    title: 'Ops Monitor & Daily Report',
    client: { en: 'Internal operations', ar: 'العمليات الداخلية' },
    year: '2026',
    status: internal,
    tagline: {
      en: 'Every workflow watched, every failure retried, one daily report on WhatsApp and Telegram.',
      ar: 'كل مسار عمل مُراقَب، وكل فشل يُعاد، وتقرير يومي واحد على واتساب وتيليجرام.',
    },
    summary: {
      en: 'The automation that watches the automations.',
      ar: 'الأتمتة التي تراقب الأتمتة.',
    },
    challenge: {
      en: 'With dozens of workflows running, silent failures were the real risk — a broken token could stop publishing for a week before anyone noticed.',
      ar: 'مع عشرات المسارات العاملة، كان الفشل الصامت هو الخطر الحقيقي — رمز منتهي قد يوقف النشر أسبوعًا قبل أن يلاحظ أحد.',
    },
    solution: {
      en: 'A health-monitor workflow that checks executions and services, a retry workflow for failed posts, WhatsApp/Telegram alerts and a daily operations report summarising what ran, what failed and what was fixed.',
      ar: 'مسار مراقبة صحة يفحص التنفيذات والخدمات، ومسار إعادة محاولة للمنشورات الفاشلة، وتنبيهات واتساب وتيليجرام، وتقرير تشغيل يومي يلخّص ما عمل وما فشل وما أُصلح.',
    },
    outcome: {
      en: 'Failures surface in minutes instead of days, and most fix themselves.',
      ar: 'الأعطال تظهر في دقائق بدل أيام، ومعظمها يُصلح نفسه.',
    },
    features: {
      en: ['Health checks', 'Auto-retry', 'WhatsApp + Telegram alerts', 'Daily ops report'],
      ar: ['فحوصات الصحة', 'إعادة محاولة تلقائية', 'تنبيهات واتساب وتيليجرام', 'تقرير تشغيل يومي'],
    },
    stack: ['n8n', 'Telegram', 'WhatsApp', 'Docker', 'Oracle Cloud'],
    role: { en: 'Design & build', ar: 'التصميم والبناء' },
    flow: {
      en: ['Cron', 'Check workflows', 'Failure?', 'Retry', 'Alert', 'Daily report'],
      ar: ['جدولة', 'فحص المسارات', 'فشل؟', 'إعادة', 'تنبيه', 'تقرير يومي'],
    },
  },
  {
    slug: 'ai-sales-widget',
    category: 'automation',
    title: 'AI Sales Assistant Widget',
    client: { en: 'Al Sakr Online', ar: 'الصقر أونلاين' },
    year: '2026',
    status: live,
    url: 'https://alsakronline.com',
    tagline: {
      en: 'An on-site assistant that answers technical questions and turns them into quotation requests.',
      ar: 'مساعد داخل الموقع يجيب عن الأسئلة الفنية ويحوّلها إلى طلبات عروض أسعار.',
    },
    summary: {
      en: 'A lightweight embeddable widget, a secure PHP proxy and an n8n brain.',
      ar: 'أداة خفيفة قابلة للتضمين، ووسيط PHP آمن، وعقل في n8n.',
    },
    challenge: {
      en: 'Engineers arrive with a part number and a question at 11 pm. Without an answer, they leave for a competitor.',
      ar: 'المهندس يصل برقم قطعة وسؤال في الحادية عشرة ليلًا. بدون إجابة، يذهب إلى المنافس.',
    },
    solution: {
      en: 'A vanilla-JS widget embedded in WordPress, a PHP proxy that hides keys and rate-limits, and an n8n workflow with session memory that answers from the catalogue and captures contact details for a quote.',
      ar: 'أداة JavaScript مضمّنة في WordPress، ووسيط PHP يخفي المفاتيح ويحدّ من الطلبات، ومسار n8n بذاكرة جلسة يجيب من الكتالوج ويجمع بيانات التواصل لعرض السعر.',
    },
    outcome: {
      en: 'Out-of-hours questions get answered and captured as leads instead of lost.',
      ar: 'أسئلة ما بعد ساعات العمل تُجاب وتُسجَّل كعملاء محتملين بدل أن تضيع.',
    },
    features: {
      en: ['Embeddable widget', 'Key-hiding proxy', 'Session memory', 'Lead capture'],
      ar: ['أداة قابلة للتضمين', 'وسيط يخفي المفاتيح', 'ذاكرة جلسة', 'جمع العملاء المحتملين'],
    },
    stack: ['JavaScript', 'PHP', 'n8n', 'LLM API', 'WordPress'],
    role: { en: 'Design & build', ar: 'التصميم والبناء' },
    flow: {
      en: ['Visitor question', 'Widget', 'PHP proxy', 'n8n + AI', 'Answer', 'Quote lead'],
      ar: ['سؤال الزائر', 'الأداة', 'وسيط PHP', 'n8n + ذكاء', 'إجابة', 'طلب سعر'],
    },
  },

  // ───────────────────────────── LAB ─────────────────────────────
  {
    slug: 'jarvis',
    category: 'lab',
    title: 'Jarvis',
    client: { en: 'Personal R&D', ar: 'بحث وتطوير شخصي' },
    year: '2026',
    status: { en: 'Daily use', ar: 'استخدام يومي' },
    tagline: {
      en: 'A voice-driven AI ops assistant with a HUD that knows what my AI coding sessions are doing.',
      ar: 'مساعد تشغيل صوتي بالذكاء الاصطناعي مع لوحة عرض تعرف ماذا تفعل جلسات البرمجة بالذكاء الاصطناعي.',
    },
    summary: {
      en: 'Ask “what needs me?” and get an answer in ~0.13 seconds — no model call required.',
      ar: 'اسأل «ما الذي يحتاجني؟» واحصل على الإجابة في نحو 0.13 ثانية — بدون استدعاء أي نموذج.',
    },
    challenge: {
      en: 'Running many AI agents in parallel means constantly checking which one is waiting for you.',
      ar: 'تشغيل عدة وكلاء ذكاء اصطناعي بالتوازي يعني التحقّق المستمر من أيّهم ينتظرك.',
    },
    solution: {
      en: 'Ported and hardened open-source pieces to Windows (including a fix that stopped a process probe from killing live sessions), added a session report, a HUD panel and local voice intents that answer instantly from the filesystem.',
      ar: 'نقلت أجزاء مفتوحة المصدر إلى ويندوز وقوّيتها (منها إصلاح منع أداة فحص من إنهاء الجلسات الحيّة)، وأضفت تقرير جلسات ولوحة عرض وأوامر صوتية محلية تجيب فورًا من نظام الملفات.',
    },
    outcome: {
      en: 'A personal command centre — and a testbed for the agents that later ship to clients.',
      ar: 'مركز قيادة شخصي — وبيئة اختبار للوكلاء الذين يُسلَّمون لاحقًا للعملاء.',
    },
    features: {
      en: ['Voice intents', 'Session watcher', 'HUD', 'Tests guarding unsafe calls'],
      ar: ['أوامر صوتية', 'مراقبة الجلسات', 'لوحة عرض', 'اختبارات تمنع الاستدعاءات الخطرة'],
    },
    stack: ['Python', 'psutil', 'TTS / STT', 'Claude', 'pytest'],
    role: { en: 'Builder', ar: 'المطوّر' },
    flow: {
      en: ['Voice', 'Intent', 'Local answer?', 'Agent', 'HUD + speech'],
      ar: ['صوت', 'نيّة', 'إجابة محلية؟', 'وكيل', 'لوحة + كلام'],
    },
  },
  {
    slug: 'video-factory',
    category: 'lab',
    title: 'Automated Video Factory',
    client: { en: 'R&D', ar: 'بحث وتطوير' },
    year: '2026',
    status: { en: 'Planning', ar: 'مرحلة التخطيط' },
    tagline: {
      en: 'Topic → script → AI presenter → voice & captions → Telegram approval → scheduled YouTube publishing.',
      ar: 'موضوع ← سيناريو ← مقدّم بالذكاء الاصطناعي ← صوت وترجمة ← موافقة تيليجرام ← نشر مجدول على يوتيوب.',
    },
    summary: {
      en: 'A costed blueprint for faceless video at scale — and an honest audit of where the hype breaks.',
      ar: 'مخطط بتكلفة محسوبة لفيديو بلا وجه على نطاق واسع — وتقييم صريح لأين تنكسر المبالغات.',
    },
    challenge: {
      en: 'Fully AI-generated 11-minute videos sound great until you price them: hundreds of dollars per video and a presenter whose face drifts between clips.',
      ar: 'فيديوهات من 11 دقيقة مولّدة بالكامل بالذكاء الاصطناعي تبدو رائعة حتى تحسب تكلفتها: مئات الدولارات للفيديو ومقدّم يتغيّر وجهه بين اللقطات.',
    },
    solution: {
      en: 'A redesigned 7-phase pipeline: short presenter segments + B-roll and motion graphics, identity locked from one portrait, TTS and captions, a Telegram approval gate and CTR-based title/thumbnail swaps — taking the estimated cost from $300–600 down to $40–80 per video.',
      ar: 'خط إنتاج من 7 مراحل مُعاد تصميمه: مقاطع قصيرة للمقدّم مع لقطات داعمة ورسوم متحركة، وهوية ثابتة من صورة واحدة، وصوت وترجمة، وبوابة موافقة تيليجرام، وتبديل العناوين والصور حسب نسبة النقر — لتنخفض التكلفة التقديرية من 300–600 دولار إلى 40–80 دولارًا للفيديو.',
    },
    outcome: {
      en: 'Business plan and build guide complete; build scheduled.',
      ar: 'خطة العمل ودليل البناء مكتملان، والبناء مُجدول.',
    },
    features: {
      en: ['Cost model', 'Hybrid AI video', 'Approval gate', 'CTR optimisation'],
      ar: ['نموذج تكلفة', 'فيديو ذكاء اصطناعي هجين', 'بوابة موافقة', 'تحسين نسبة النقر'],
    },
    stack: ['n8n', 'Veo', 'TTS', 'FFmpeg', 'YouTube API', 'Telegram'],
    role: { en: 'Strategy & architecture', ar: 'الاستراتيجية والمعمارية' },
    flow: {
      en: ['Topic', 'Script', 'Scenes', 'Voice + captions', 'Approve', 'Publish'],
      ar: ['موضوع', 'سيناريو', 'مشاهد', 'صوت + ترجمة', 'موافقة', 'نشر'],
    },
  },
];

export const categories: Category[] = ['web', 'system', 'automation', 'lab'];
export const featuredProjects = projects.filter((p) => p.featured);
export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
